name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.craftaro.epiclevels.EpicLevels
softdepend:
  - Vault
  - PlaceholderAPI

author: Craftaro
website: ${project.url}

commands:
  EpicLevels:
    default: true
    aliases: [ el, levels, level ]
    usage: /levels
